//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpVotes.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.CompanyBranch = new HashSet<CompanyBranch>();
            this.CompanyFocus = new HashSet<CompanyFocus>();
            this.CompanyPortFolio = new HashSet<CompanyPortFolio>();
        }
    
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string LogoName { get; set; }
        public string TagLine { get; set; }
        public int FoundedYear { get; set; }
        public int EmployeeCount { get; set; }
        public Nullable<decimal> AvgHourleyRate { get; set; }
        public string URL { get; set; }
        public string LinkedInProfileURL { get; set; }
        public string TwitterProfileURL { get; set; }
        public string FacebookProfileURL { get; set; }
        public string GooglePlusProfileURL { get; set; }
        public string Summary { get; set; }
        public string KeyClients { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyBranch> CompanyBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyFocus> CompanyFocus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyPortFolio> CompanyPortFolio { get; set; }
    }
}
